/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/MDIApplication.java to edit this template
 */
package proyecto;

import ConexionDB.ConexionDB;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JOptionPane;

/**
 *
 * @author MILTON PAZ
 */
public class MenuPrincipal extends javax.swing.JFrame {

    Connection con = null;
    ConexionDB conecta;
    String usuario, sentenciaSQL;
    PreparedStatement ps = null;
    ResultSet rs = null;

    public MenuPrincipal() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    public void conectarBD() {
        conecta = new ConexionDB("gimnasio");
        con = conecta.getConexion();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        contenedorMenu = new javax.swing.JDesktopPane();
        jPanel1 = new javax.swing.JPanel();
        btnSALIR = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        menuBar = new javax.swing.JMenuBar();
        menuClientes = new javax.swing.JMenu();
        menuMembresias = new javax.swing.JMenu();
        menuHorarios = new javax.swing.JMenu();
        menuMensajeria = new javax.swing.JMenu();
        menuFacturacion = new javax.swing.JMenu();
        menuControl = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnSALIR.setBackground(new java.awt.Color(255, 255, 255));
        btnSALIR.setFont(new java.awt.Font("Dialog", 1, 13)); // NOI18N
        btnSALIR.setForeground(new java.awt.Color(255, 0, 0));
        btnSALIR.setText("SALIR");
        btnSALIR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSALIRActionPerformed(evt);
            }
        });
        jPanel1.add(btnSALIR, new org.netbeans.lib.awtextra.AbsoluteConstraints(1050, 590, 130, 50));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/fondoMain.jpg"))); // NOI18N
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1200, 660));

        contenedorMenu.setLayer(jPanel1, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout contenedorMenuLayout = new javax.swing.GroupLayout(contenedorMenu);
        contenedorMenu.setLayout(contenedorMenuLayout);
        contenedorMenuLayout.setHorizontalGroup(
            contenedorMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        contenedorMenuLayout.setVerticalGroup(
            contenedorMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 661, Short.MAX_VALUE)
        );

        menuClientes.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/clientes.png"))); // NOI18N
        menuClientes.setMnemonic('h');
        menuClientes.setText("CLIENTES");
        menuClientes.setFont(new java.awt.Font("Perpetua Titling MT", 1, 12)); // NOI18N
        menuClientes.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                menuClientesMouseClicked(evt);
            }
        });
        menuClientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuClientesActionPerformed(evt);
            }
        });
        menuBar.add(menuClientes);

        menuMembresias.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/membresias.png"))); // NOI18N
        menuMembresias.setMnemonic('h');
        menuMembresias.setText("MEMBRESIAS");
        menuMembresias.setFont(new java.awt.Font("Perpetua Titling MT", 1, 12)); // NOI18N
        menuMembresias.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                menuMembresiasMouseClicked(evt);
            }
        });
        menuBar.add(menuMembresias);

        menuHorarios.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/horario.png"))); // NOI18N
        menuHorarios.setMnemonic('h');
        menuHorarios.setText("HORARIOS");
        menuHorarios.setFont(new java.awt.Font("Perpetua Titling MT", 1, 12)); // NOI18N
        menuHorarios.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                menuHorariosMouseClicked(evt);
            }
        });
        menuBar.add(menuHorarios);

        menuMensajeria.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/mensaje.png"))); // NOI18N
        menuMensajeria.setMnemonic('h');
        menuMensajeria.setText("MENSAJERIA");
        menuMensajeria.setFont(new java.awt.Font("Perpetua Titling MT", 1, 12)); // NOI18N
        menuBar.add(menuMensajeria);

        menuFacturacion.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/facturacion.png"))); // NOI18N
        menuFacturacion.setMnemonic('h');
        menuFacturacion.setText("FACTURACION");
        menuFacturacion.setFont(new java.awt.Font("Perpetua Titling MT", 1, 12)); // NOI18N
        menuFacturacion.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                menuFacturacionMouseClicked(evt);
            }
        });
        menuBar.add(menuFacturacion);

        menuControl.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/access.png"))); // NOI18N
        menuControl.setMnemonic('h');
        menuControl.setText("CONTROL DE ACCESO");
        menuControl.setFont(new java.awt.Font("Perpetua Titling MT", 1, 12)); // NOI18N
        menuControl.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                menuControlMouseClicked(evt);
            }
        });
        menuBar.add(menuControl);

        setJMenuBar(menuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(contenedorMenu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(contenedorMenu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSALIRActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSALIRActionPerformed
        System.exit(0);
    }//GEN-LAST:event_btnSALIRActionPerformed

    private void menuMembresiasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menuMembresiasMouseClicked
        Membresias jframe = new Membresias();
        contenedorMenu.add(jframe);
        jframe.show();
    }//GEN-LAST:event_menuMembresiasMouseClicked

    private void menuClientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuClientesActionPerformed
        
    }//GEN-LAST:event_menuClientesActionPerformed

    private void menuClientesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menuClientesMouseClicked
        Clientes jframe = new Clientes();
        contenedorMenu.add(jframe);
        jframe.show();
    }//GEN-LAST:event_menuClientesMouseClicked

    private void menuControlMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menuControlMouseClicked
        ControlAcceso jframe = new ControlAcceso();
        contenedorMenu.add(jframe);
        jframe.show();
    }//GEN-LAST:event_menuControlMouseClicked


    private void menuFacturacionMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menuFacturacionMouseClicked
        _Facturacion jframe = new _Facturacion();
        contenedorMenu.add(jframe);
        jframe.show();
    }//GEN-LAST:event_menuFacturacionMouseClicked

    private void menuHorariosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menuHorariosMouseClicked

    }//GEN-LAST:event_menuHorariosMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MenuPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSALIR;
    private javax.swing.JDesktopPane contenedorMenu;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JMenuBar menuBar;
    public static javax.swing.JMenu menuClientes;
    public static javax.swing.JMenu menuControl;
    public static javax.swing.JMenu menuFacturacion;
    public static javax.swing.JMenu menuHorarios;
    public static javax.swing.JMenu menuMembresias;
    public static javax.swing.JMenu menuMensajeria;
    // End of variables declaration//GEN-END:variables

}
